const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const adminPdfService = {
    // Generate Citizens Report
    generateCitizensReport: (data, wardName, generatedByName) => {
        return new Promise((resolve, reject) => {
            const fileName = `Citizens_Report_${Date.now()}.pdf`;
            const filePath = path.join(__dirname, '../uploads/reports', fileName);
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            // Header
            adminPdfService.addHeader(doc, `CITIZENS REPORT - ${wardName.toUpperCase()} WARD`);
            doc.fontSize(10).fillColor('#666666').text(`Generated By: ${generatedByName}`, { align: 'right' });
            doc.moveDown(0.5);
            doc.fontSize(12).fillColor('#333333').text(`Total Citizens: ${data.citizens.length}`, { underline: true });
            doc.moveDown(1);

            // Citizens Table
            if (data.citizens.length > 0) {
                adminPdfService.drawTable(doc, data.citizens, [
                    { header: '#', width: 30, key: 'index' },
                    { header: 'Full Name', width: 120, key: 'full_name' },
                    { header: 'Phone', width: 90, key: 'phone' },
                    { header: 'Status', width: 70, key: 'status' },
                    { header: 'Reg. Date', width: 80, key: 'registration_date' }
                ]);
            }

            // Summary Stats
            doc.moveDown(1);
            doc.fontSize(12).fillColor('#1a5276').text('Summary Statistics', { underline: true });
            doc.moveDown(0.5);
            const active = data.citizens.filter(c => c.status === 'active').length;
            const inactive = data.citizens.filter(c => c.status === 'inactive').length;
            doc.fontSize(10).fillColor('#333333');
            doc.text(`Active Citizens: ${active}`);
            doc.text(`Inactive Citizens: ${inactive}`);

            adminPdfService.addFooter(doc);
            doc.end();

            stream.on('finish', () => resolve({ filePath, fileName }));
            stream.on('error', reject);
        });
    },

    // Generate Payments Report
    generatePaymentsReport: (data, wardName, generatedByName) => {
        return new Promise((resolve, reject) => {
            const fileName = `Payments_Report_${Date.now()}.pdf`;
            const filePath = path.join(__dirname, '../uploads/reports', fileName);
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            adminPdfService.addHeader(doc, `PAYMENTS REPORT - ${wardName.toUpperCase()} WARD`);
            doc.fontSize(10).fillColor('#666666').text(`Generated By: ${generatedByName}`, { align: 'right' });
            doc.moveDown(0.5);

            const totalRevenue = data.payments.reduce((sum, p) => sum + parseFloat(p.amount || 0), 0);
            doc.fontSize(12).fillColor('#333333');
            doc.text(`Total Payments: ${data.payments.length}`);
            doc.text(`Total Revenue: TZS ${totalRevenue.toLocaleString()}`, { underline: true });
            doc.moveDown(1);

            if (data.payments.length > 0) {
                adminPdfService.drawTable(doc, data.payments, [
                    { header: '#', width: 30, key: 'index' },
                    { header: 'Payment ID', width: 100, key: 'payment_id' },
                    { header: 'Citizen', width: 100, key: 'citizen_name' },
                    { header: 'Amount', width: 70, key: 'amount' },
                    { header: 'Method', width: 70, key: 'payment_method' },
                    { header: 'Status', width: 60, key: 'payment_status' }
                ]);
            }

            adminPdfService.addFooter(doc);
            doc.end();

            stream.on('finish', () => resolve({ filePath, fileName }));
            stream.on('error', reject);
        });
    },

    // Generate Documents Report
    generateDocumentsReport: (data, wardName, generatedByName) => {
        return new Promise((resolve, reject) => {
            const fileName = `Documents_Report_${Date.now()}.pdf`;
            const filePath = path.join(__dirname, '../uploads/reports', fileName);
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            adminPdfService.addHeader(doc, `DOCUMENTS REPORT - ${wardName.toUpperCase()} WARD`);
            doc.fontSize(10).fillColor('#666666').text(`Generated By: ${generatedByName}`, { align: 'right' });
            doc.moveDown(0.5);
            doc.fontSize(12).fillColor('#333333').text(`Total Requests: ${data.documents.length}`, { underline: true });
            doc.moveDown(1);

            if (data.documents.length > 0) {
                adminPdfService.drawTable(doc, data.documents, [
                    { header: '#', width: 30, key: 'index' },
                    { header: 'Citizen', width: 100, key: 'citizen_name' },
                    { header: 'Document Type', width: 120, key: 'document_type' },
                    { header: 'Payment', width: 70, key: 'payment_status' },
                    { header: 'Status', width: 70, key: 'request_status' }
                ]);
            }

            adminPdfService.addFooter(doc);
            doc.end();

            stream.on('finish', () => resolve({ filePath, fileName }));
            stream.on('error', reject);
        });
    },

    // Generate System Report
    generateSystemReport: (data, wardName, generatedByName) => {
        return new Promise((resolve, reject) => {
            const fileName = `System_Report_${Date.now()}.pdf`;
            const filePath = path.join(__dirname, '../uploads/reports', fileName);
            const doc = new PDFDocument({ margin: 50, size: 'A4' });
            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            adminPdfService.addHeader(doc, `SYSTEM REPORT - ${wardName.toUpperCase()} WARD`);
            doc.fontSize(10).fillColor('#666666').text(`Generated By: ${generatedByName}`, { align: 'right' });
            doc.moveDown(1);

            // Summary
            doc.fontSize(14).fillColor('#1a5276').text('1. Summary', { underline: true });
            doc.moveDown(0.3);
            doc.fontSize(11).fillColor('#333333');
            doc.text(`Total Citizens: ${data.summary.total_citizens}`);
            doc.text(`Active Citizens: ${data.summary.active_citizens}`);
            doc.text(`Total Revenue: TZS ${data.summary.total_revenue.toLocaleString()}`);
            doc.text(`Documents Issued: ${data.summary.documents_issued}`);
            doc.moveDown(1);

            // Citizens
            doc.fontSize(14).fillColor('#1a5276').text('2. Citizens', { underline: true });
            doc.moveDown(0.3);
            if (data.citizens && data.citizens.length > 0) {
                adminPdfService.drawTable(doc, data.citizens.slice(0, 15), [
                    { header: '#', width: 30, key: 'index' },
                    { header: 'Full Name', width: 130, key: 'full_name' },
                    { header: 'Phone', width: 90, key: 'phone' },
                    { header: 'Status', width: 70, key: 'status' }
                ]);
            }
            doc.moveDown(1);

            // Payments
            doc.fontSize(14).fillColor('#1a5276').text('3. Recent Payments', { underline: true });
            doc.moveDown(0.3);
            if (data.payments && data.payments.length > 0) {
                adminPdfService.drawTable(doc, data.payments.slice(0, 10), [
                    { header: '#', width: 30, key: 'index' },
                    { header: 'Payment ID', width: 100, key: 'payment_id' },
                    { header: 'Citizen', width: 90, key: 'citizen_name' },
                    { header: 'Amount', width: 70, key: 'amount' }
                ]);
            }

            adminPdfService.addFooter(doc);
            doc.end();

            stream.on('finish', () => resolve({ filePath, fileName }));
            stream.on('error', reject);
        });
    },

    // Header Helper
    addHeader: (doc, title) => {
        doc.fontSize(20).fillColor('#1a5276').text('LAMS', { align: 'center' });
        doc.fontSize(9).fillColor('#666666').text('Local Administration Management System', { align: 'center' });
        doc.moveDown(0.3);
        doc.fontSize(14).fillColor('#333333').text(title, { align: 'center' });
        doc.moveDown(0.3);
        doc.fontSize(8).fillColor('#999999').text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
        doc.moveDown(0.5);
        doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown(0.5);
    },

    // Footer Helper
    addFooter: (doc) => {
        const bottom = doc.page.height - 50;
        doc.fontSize(8).fillColor('#999999');
        doc.text(`Page ${doc.bufferedPageRange().start + 1}`, 50, bottom, { align: 'center', width: 500 });
        doc.text('LAMS - Confidential Report', 50, bottom + 12, { align: 'center', width: 500 });
    },

    // Table Helper
    drawTable: (doc, rows, columns) => {
        const tableTop = doc.y;
        const colWidths = columns.map(c => c.width);
        const totalWidth = colWidths.reduce((a, b) => a + b, 0);

        // Header row
        doc.fontSize(7).fillColor('#ffffff');
        doc.rect(50, tableTop, totalWidth, 16).fill('#1a5276');
        let xPos = 52;
        columns.forEach((col) => {
            doc.fillColor('#ffffff').text(col.header, xPos, tableTop + 4, { width: col.width - 5 });
            xPos += col.width;
        });

        // Data rows
        let yPos = tableTop + 16;
        doc.fontSize(7);
        rows.forEach((row, index) => {
            if (yPos > 720) {
                doc.addPage();
                yPos = 50;
            }

            const bgColor = index % 2 === 0 ? '#f8f9fa' : '#ffffff';
            doc.rect(50, yPos, totalWidth, 14).fill(bgColor);

            xPos = 52;
            columns.forEach((col) => {
                let value = col.key === 'index' ? (index + 1).toString() : (row[col.key] || '');
                if (col.key === 'amount') value = parseFloat(value).toLocaleString();
                if (col.key === 'registration_date' || col.key === 'payment_date') {
                    value = value ? new Date(value).toLocaleDateString() : '';
                }
                doc.fillColor('#333333').text(value.toString(), xPos, yPos + 2, { width: col.width - 5 });
                xPos += col.width;
            });

            yPos += 14;
        });

        doc.moveDown(2);
    }
};

module.exports = adminPdfService;