const nodemailer = require('nodemailer');
require('dotenv').config();

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
    }
});

const sendOTPEmail = async (email, otp) => {
    const mailOptions = {
        from: process.env.EMAIL_USER,
        to: email,
        subject: 'LAMS - OTP Verification',
        html: `
            <h2>Your OTP Code</h2>
            <p>Use the following OTP to verify your account:</p>
            <h1 style="color: #4CAF50; font-size: 32px;">${otp}</h1>
            <p>This OTP expires in 10 minutes.</p>
        `
    };

    await transporter.sendMail(mailOptions);
};

const sendResetPasswordEmail = async (email, resetToken) => {
    const mailOptions = {
        from: process.env.EMAIL_USER,
        to: email,
        subject: 'LAMS - Reset Password',
        html: `
            <h2>Password Reset Request</h2>
            <p>Use the following token to reset your password:</p>
            <h1 style="color: #FF5722; font-size: 24px;">${resetToken}</h1>
            <p>This token expires in 10 minutes.</p>
        `
    };

    await transporter.sendMail(mailOptions);
};

const sendReportEmail = async (recipientEmail, report, generatedByName) => {
    const mailOptions = {
        from: process.env.EMAIL_USER,
        to: recipientEmail,
        subject: `LAMS - ${report.report_name}`,
        html: `
            <h2>LAMS Report</h2>
            <p>Dear Recipient,</p>
            <p>Please find attached the following report:</p>
            <table style="border-collapse: collapse; width: 100%; max-width: 500px;">
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Report Name</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${report.report_name}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Report Type</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${report.report_type}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Records</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${report.record_count}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Generated By</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${generatedByName}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Generated Date</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${new Date(report.created_at).toLocaleString()}</td>
                </tr>
            </table>
            <p style="margin-top: 20px;">Please visit the LAMS portal to download the full report.</p>
            <p>Regards,<br>LAMS Administration</p>
        `
    };

    // Attach file if exists
    if (report.file_path) {
        const path = require('path');
        const fs = require('fs');
        const filePath = report.file_path;
        
        if (fs.existsSync(filePath)) {
            mailOptions.attachments = [
                {
                    filename: path.basename(filePath),
                    path: filePath
                }
            ];
        }
    }

    await transporter.sendMail(mailOptions);
};

module.exports = { sendOTPEmail, sendResetPasswordEmail, sendReportEmail };